spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    numPartitions: 3
    fileChunks: file-chunks

fileaxe:
  chunkSize: 600000

storage:
  location: "storage"
